#!/bin/bash
# =============================================================================
# KIBI MONETIZER AGENT — autonomous self-monetization agent for the Kibi side
# of One Dollar Quest. Runs headless, no LLM needed (LLM optional via Kibi
# Gateway once credits exist: set KIBI_LLM=1 and it will use it for decisions).
#
# Loop (every MONETIZE_INTERVAL_MIN, default 30):
#   1. HEARTBEAT      — revenue & assets snapshot (kibi fees, x402 health)
#   2. LAUNCH QUEUE   — if BNB/Base quota free, delegate to monitor_v2 logic
#   3. TREND SCAN     — every TREND_SCAN_HOURS: trending BSC pools -> queue
#   4. CONTENT        — every CONTENT_HOURS: regenerate diffusion post drafts
#   5. OPPORTUNITY    — if any x402 endpoint 500s/dies, log + update profile desc
#
# State: /home/z/my-project/scripts/monetizer_state.json
# Log:   /home/z/my-project/scripts/monetizer.log
# =============================================================================
export PATH="/home/z/.npm-global/bin:$PATH"
source /home/z/my-project/secrets/keys.env 2>/dev/null

BASE=/home/z/my-project
STATE=$BASE/scripts/monetizer_state.json
LOG=$BASE/scripts/monetizer.log
CONTENT=$BASE/download/post_difusion_x402_BORRADOR.md
INTERVAL=${MONETIZE_INTERVAL_MIN:-30}
VENDOR="0xf436ca41bd0a236338bef57adeb4976677513010"

[ -f "$STATE" ] || echo '{"trend_queue":[],"content_last":0,"trend_last":0,"cycles":0}' > "$STATE"
log() { echo "[$(date -u +%FT%TZ)] $1" >> "$LOG"; }

# ---------- 1. heartbeat ----------
heartbeat() {
  local fees x402_health
  fees=$(kibi fees --json 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); b=d.get('bsc',{}); print(f\"kibi_fees_bnb={b.get('total_earned_bnb',0)} tokens={b.get('token_count',0)}\")" 2>/dev/null)
  # x402 health: all 5 endpoints must answer 402 (paywall live)
  local dead=0
  for svc in market-signal pair-scan token-safety funding-heatmap crypto-sentinel; do
    code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "https://x402.bankr.bot/$VENDOR/$svc?coin=bitcoin&token=0x613B6c32bAFF797108417F0b653738547F5b7777&symbol=BTC")
    [ "$code" != "402" ] && [ "$code" != "200" ] && { dead=$((dead+1)); log "ALERT: $svc unhealthy HTTP $code"; }
  done
  log "heartbeat: $fees | x402 dead endpoints: $dead/5"
  echo "$dead"
}

# ---------- 3. trend scan ----------
trend_scan() {
  local now=$(date +%s); local last=$(python3 -c "import json;print(json.load(open('$STATE')).get('trend_last',0))")
  [ $((now - last)) -lt $(( ${TREND_SCAN_HOURS:-6} * 3600 )) ] && return
  curl -s --max-time 20 "https://api.geckoterminal.com/api/v2/networks/bsc/trending_pools?include=base_token" -H "Accept: application/json" -o /tmp/gt_m.json
  python3 - << 'EOF' >> "$LOG"
import json, re
try:
    d = json.load(open('/tmp/gt_m.json'))
    included = {i['id']: i for i in d.get('included', [])}
    rows = []
    for p in d.get('data', [])[:12]:
        a = p.get('attributes', {})
        rel = p.get('relationships', {}).get('base_token', {}).get('data', {})
        tid = rel.get('id') if isinstance(rel, dict) else None
        tk = (included.get(tid) or {}).get('attributes', {}) if tid else {}
        sym = tk.get('symbol')
        if not sym:  # fallback: parse from pool name "ABC / WBNB"
            m = re.match(r'\$?([A-Za-z0-9]+)\s*/', a.get('name', ''))
            sym = m.group(1) if m else None
        try: vol = float(a.get('volume_usd', {}).get('h24') or 0)
        except: vol = 0
        if sym: rows.append((sym, vol))
    rows.sort(key=lambda x: -x[1])
    st = json.load(open('/home/z/my-project/scripts/monetizer_state.json'))
    st['trend_queue'] = [r[0] for r in rows[:6]]
    st['trend_last'] = int(__import__('time').time())
    json.dump(st, open('/home/z/my-project/scripts/monetizer_state.json', 'w'))
    print(f"trend_scan: top symbols {st['trend_queue']} queued for naming inspiration")
except Exception as e:
    print(f"trend_scan error: {e}")
EOF
}

# ---------- 4. content refresh ----------
content_refresh() {
  local now=$(date +%s); local last=$(python3 -c "import json;print(json.load(open('$STATE')).get('content_last',0))")
  [ $((now - last)) -lt $(( ${CONTENT_HOURS:-12} * 3600 )) ] && return
  local fees ts
  fees=$(kibi fees --json 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('bsc',{}).get('total_earned_bnb',0))" 2>/dev/null)
  ts=$(date -u +%FT%TZ)
  cat >> "$CONTENT" << EOF

---
## DRAFT (auto-generated by kibi_monetizer at $ts — human review required before posting)

🤖 One Dollar Quest update:
• 5 live paid crypto APIs (x402, pay per call from \$0.001 in USDC — no signup, your wallet is the subscription)
• Portfolio tokens on BNB: ZTOD, AFEE (+ Agent Banana launching) — creator fees fund the experiment: currently ${fees:-0} BNB earned
• Full open-source stack (consumer agent, skills, automation): github.com/perria080925-bot/one-dollar-quest
• Built end-to-end by an autonomous AI agent. Experimental, no promises. DYOR.

#AIagents #x402 #BNBChain #Base #CryptoAPI
EOF
  python3 -c "
import json; st=json.load(open('$STATE')); st['content_last']=$(date +%s); json.dump(st, open('$STATE','w'))"
  log "content_refresh: new draft appended to $CONTENT"
}

# ---------- main ----------
log "=== monetizer agent started (PID $$, interval ${INTERVAL}min) ==="
CYCLES=0
while true; do
  CYCLES=$((CYCLES+1))
  DEAD=$(heartbeat)
  trend_scan
  content_refresh
  python3 -c "
import json; st=json.load(open('$STATE')); st['cycles']=$CYCLES; json.dump(st, open('$STATE','w'))"
  sleep $(( INTERVAL * 60 ))
done
